### ISSUE TITLE
Add support to YoloV3-Tiny-PRN

### ISSUE THREAD

**Issue by marcoslucianops** [ceccocats/tkDNN#6]
Can you add support to [YoloV3-Tiny-PRN](https://github.com/WongKinYiu/PartialResidualNetworks)?

![image](https://user-images.githubusercontent.com/4096485/71702416-6645dc00-2de0-11ea-8d65-de7d4b604021.png)

**Comment by ceccocats** [comment]
Hi,
Although this net is very small and easy to port we cant implement every network in the world.
In this repo there are the dnn that are interesting for us.
Since we use a lot of work from darknet in the future I probably will create a parser for darknet cfg to automatically import; But right now you have to manually write your own network.

**Comment by ceccocats** [comment]
The parser is now avaible
https://github.com/ceccocats/tkDNN#darknet-parser
