### ISSUE TITLE
webcam

### ISSUE THREAD

**Issue by xxd1999** [ceccocats/tkDNN#96]
Hi!I want test on my jetson nano with an  usb camera.What should I replace with the command "./demo yolo3_fp32.rt ../demo/yolo_test.mp4 y"?Thanks.

**Comment by ceccocats** [comment]
I think you can substitute yolo_test.mp4 with /dev/video0 but you will have a lot of lag because the Jetson nano is not capable to process 30 fps (typical webcam frame rate) in real-time.
To solve this you should divide the webcam reader and the inference in 2 threads or drop frames from camera when reading to keep only the last one.
